### ISSUE TITLE
Visual focus fix is not applied to keyboard interaction

### ISSUE THREAD

**Issue by gapple** [yaleux/yaleui#1] opened 2016-07-23 00:08 UTC
The override of foundation removing the outline from elements on focus is only applied to mouse interaction, leaving keyboard users without any indication of the active element:

yaleui/src/assets/scss/_visual-focus-fix.scss

```
[data-whatinput='mouse'] *:focus {
  outline: auto !important; }
```

**Comment by michaelwayneharris87** [comment] 2016-07-23 20:13
Thanks so much for pointing this out. Can you provide steps to reproduce? I'm not 100% sure what I should be looking for.

**Comment by adrianacorona** [comment] 2016-08-10 13:49
@gapple, the visual focus fix is applied to mouse interactions because those were the instances were `outline: 0` was enforced by Foundation.  We're just overwriting their defaults; they never set `outline: 0` to keyboard interactions, so this should be ok! 

Closing this issue, but please let us know if you found any occasion where keyboard interactions don't have visual focus.

**Closed as completed by adrianacorona** 2016-08-10 13:49 UTC
Labels: bug
